Cluster for demo application
mfvanek/pg-index-health-spring-boot-demo pull request #62
Opened 2023-04-04 18:10 UTC by Evreke

cluster credentials for three profiles:
* embedded-postgres - single node with testcontainers
* embedded-cluster - two node cluster with testcontainers
* external-cluster - two node cluster with externalized configuration

To test this code you have to publish 0.9.2-SNAPSHOT of pg-index-health-testing from https://github.com/mfvanek/pg-index-health/tree/feature/externalize_params

Looking forward to your participation

2023-04-09 07:18 UTC, mfvanek commented on src/main/java/io/github/mfvanek/pg/index/health/demo/config/EmbeddedPostgresConfig.java
> +public class EmbeddedPostgresConfig {
It's not Embedded

2023-04-09 07:23 UTC, mfvanek requested changes

2023-04-09 07:23 UTC, mfvanek commented on src/main/java/io/github/mfvanek/pg/index/health/demo/config/EmbeddedPostgresCredentials.java
> +public class EmbeddedPostgresCredentials {
It's not a good name. It's not `embedded`

2023-05-07 14:15 UTC, Evreke commented
I change profile names and class names according to it. Starter guide added to readme.md

2023-05-07 14:22 UTC, Evreke commented
Problem is that now we have to run tests for each profile (probably excluding external-cluster-postgres). 
We can do it with gradle.
Another problem with tests for external-cluster-postgres against external cluster. We have to exclude it's configuration from coverage or somehow run tests with that profile.

2023-05-07 16:06 UTC, mfvanek requested changes

2023-05-27 19:06 UTC, mfvanek commented
Please update PR and resolve conflicts with master branch. I've migrated to Kotlin DSL

2024-02-06 11:00 UTC, closed without merging